name: chemSpec
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.11=h7f8727e_2
  - pip=23.3=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - adjusttext==1.1.1
      - astroid==2.15.8
      - atomicwrites==1.4.1
      - attrs==23.2.0
      - certifi==2024.7.4
      - cftime==1.6.3
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - coverage==7.5.1
      - cycler==0.12.1
      - dill==0.3.7
      - entrypoints==0.3
      - exceptiongroup==1.1.3
      - flake8==3.7.9
      - flask==2.2.5
      - flask-jwt-extended==4.5.2
      - fonttools==4.43.1
      - gunicorn==23.0.0
      - idna==3.7
      - importlib-metadata==3.6.0
      - importlib-resources==5.1.3
      - iniconfig==2.0.0
      - isort==5.13.2
      - itsdangerous==2.0.0
      - jinja2==3.1.6
      - kiwisolver==1.4.5
      - lazy-object-proxy==1.10.0
      - markupsafe==2.1.2
      - matplotlib==3.7.3
      - mccabe==0.6.1
      - more-itertools==7.2.0
      - netcdf4==1.5.3
      - numpy==1.22.4
      - olefile==0.46
      - packaging==23.2
      - pandas==2.0.3
      - pathlib2==2.3.4
      - pillow==10.3.0
      - platformdirs==4.1.0
      - pluggy==0.12.0
      - py==1.11.0
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - pyjwt==2.8.0
      - pylint==2.17.7
      - pymzml==2.5.2
      - pyopenms==2.6.0
      - pyparsing==2.4.2
      - pytest==7.2.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - rdkit==2023.9.1
      - regex==2019.4.9
      - requests==2.32.4
      - scipy==1.7.3
      - six==1.11.0
      - tomli==2.0.1
      - tomlkit==0.12.3
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - urllib3==2.5.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.2
      - -e git+https://github.com/ComPlat/nmrglue.git@Refactor-parse_xy_xy-standardize-output-3D-arrays#egg=nmrglue
